job:
  url: 'https://github.com/gabrielstar/jmeter_template.git'
  jobName: 'example2'
  description: 'Description of the job'
  type: 'performance'
  environment: 'dev2'
  regression:
    enabled: true
  feature:
    enabled: true