job:
  url: 'https://github.com/gabrielstar/jmeter_template.git'
  jobName: 'example'
  description: 'Description of the job'
  type: 'selenium'
  environment: 'dev1'
  regression:
    enabled: true
  feature:
    enabled: true
  standalone:
    enabled: true
  browser: safari