job:
  description: 'Generic Job Description'
  scriptPath: 'Jenkinsfile'
  credentialsId: ''
  enabled: true
  type: 'selenium'
  environment: 'dev1'
  regression:
    branches:
      includes: '*develop'
      excludes: 'foo'
    enabled: true
    trigger: 'periodic(120)'
  feature:
    branches:
      includes: '*'
      excludes: 'master'
    enabled: true
    trigger: 'periodic(15)'
  standalone:
    branches:
      includes: 'master'
    enabled: true
  orphanedOldItemsNumKeep: 3
  orphanedOldItemsDaysKeep: 1
  oldItemsNumKeep: 10
  oldItemsDaysKeep: 10
  oldArtifactsNumKeep: 10
  oldArtifactsDaysKeep: 10
  browser: firefox